import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ecoActionsApi, quizzesApi, quizAttemptsApi, challengeProgressApi } from '@/db/api';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Award, Upload, BookOpen, Users, FileText, Gamepad2 } from 'lucide-react';
import { toast } from 'sonner';
import type { EcoActionWithDetails, QuizWithQuestions } from '@/types/types';

export default function TeacherDashboard() {
  const [pendingActions, setPendingActions] = useState<EcoActionWithDetails[]>([]);
  const [quizzes, setQuizzes] = useState<QuizWithQuestions[]>([]);
  const [quizResults, setQuizResults] = useState<any[]>([]);
  const [gameResults, setGameResults] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    try {
      const [actionsData, quizzesData, attemptsData, progressData] = await Promise.all([
        ecoActionsApi.getPendingActions(),
        quizzesApi.getAllQuizzes(),
        quizAttemptsApi.getAllAttempts(),
        challengeProgressApi.getAllProgress(),
      ]);
      setPendingActions(actionsData);
      setQuizzes(quizzesData);
      setQuizResults(attemptsData.slice(0, 10));
      setGameResults(progressData.slice(0, 10));
    } catch (error) {
      console.error('Error loading data:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleReviewAction = async (actionId: string, status: 'approved' | 'rejected') => {
    try {
      const user = await import('@/db/api').then(m => m.profilesApi.getCurrentUser());
      if (!user) return;

      await ecoActionsApi.reviewAction(actionId, status, user.id);
      toast.success(`Eco-action ${status}`);
      loadData();
    } catch (error) {
      console.error('Error reviewing action:', error);
      toast.error('Failed to review eco-action');
    }
  };

  const generateStudentReport = () => {
    const totalQuizAttempts = quizResults.length;
    const totalGamesPlayed = gameResults.length;
    const completedGames = gameResults.filter(g => g.completed).length;
    
    const report = `
=== STUDENT PERFORMANCE REPORT ===
Generated by: Teacher
Date: ${new Date().toLocaleString()}

QUIZ PERFORMANCE:
- Total Quiz Attempts: ${totalQuizAttempts}
${quizResults.slice(0, 10).map((result: any, i: number) => 
  `${i + 1}. ${result.student?.username || 'Unknown'} - ${result.quiz?.title || 'Unknown Quiz'} - Score: ${result.score}/${result.total_questions} - Points: ${result.points_earned}`
).join('\n')}

GAME PERFORMANCE:
- Total Games Played: ${totalGamesPlayed}
- Completed Games: ${completedGames}
${gameResults.slice(0, 10).map((result: any, i: number) => 
  `${i + 1}. ${result.student?.username || 'Unknown'} - ${result.challenge?.title || 'Unknown Game'} - Score: ${result.score}% - ${result.completed ? 'Completed' : 'In Progress'} - Points: ${result.points_earned}`
).join('\n')}

PENDING ECO-ACTIONS:
- Total Pending: ${pendingActions.length}
${pendingActions.slice(0, 5).map((action: any, i: number) => 
  `${i + 1}. ${action.student?.username || 'Unknown'} - ${action.title} - ${action.action_type}`
).join('\n')}

=== END OF REPORT ===
    `;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `student-report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Student report generated successfully!');
  };

  if (loading) {
    return (
      <div className="container mx-auto px-4 py-8 space-y-6">
        <Skeleton className="h-10 w-64 bg-muted" />
        <div className="grid gap-6 md:grid-cols-2">
          {[...Array(4)].map((_, i) => (
            <Card key={i}>
              <CardHeader>
                <Skeleton className="h-6 w-48 bg-muted" />
              </CardHeader>
              <CardContent>
                <Skeleton className="h-20 w-full bg-muted" />
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 py-8 space-y-8">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold gradient-text">Teacher Dashboard</h1>
          <p className="text-muted-foreground">Manage content and review student activities</p>
        </div>
        <Button onClick={generateStudentReport}>
          <FileText className="w-4 h-4 mr-2" />
          Generate Student Report
        </Button>
      </div>

      <div className="grid gap-6 md:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">My Quizzes</CardTitle>
            <Award className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{quizzes.length}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Pending Reviews</CardTitle>
            <Upload className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{pendingActions.length}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Quiz Attempts</CardTitle>
            <FileText className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{quizResults.length}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Game Completions</CardTitle>
            <Gamepad2 className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{gameResults.length}</div>
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        <Card className="shadow-elegant">
          <CardHeader>
            <CardTitle>Content Management</CardTitle>
            <CardDescription>Create and manage educational content</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            <Button asChild className="w-full" variant="outline">
              <Link to="/quizzes">
                <Award className="w-4 h-4 mr-2" />
                Add/Edit Quizzes
              </Link>
            </Button>
            <Button asChild className="w-full" variant="outline">
              <Link to="/challenges">
                <Gamepad2 className="w-4 h-4 mr-2" />
                Add/Edit Games
              </Link>
            </Button>
            <Button asChild className="w-full" variant="outline">
              <Link to="/learn">
                <BookOpen className="w-4 h-4 mr-2" />
                Add/Edit Learning Modules
              </Link>
            </Button>
            <Button asChild className="w-full" variant="outline">
              <Link to="/leaderboard">
                <Users className="w-4 h-4 mr-2" />
                View Student Leaderboard
              </Link>
            </Button>
            <Button asChild className="w-full" variant="outline">
              <Link to="/eco-actions">
                <Upload className="w-4 h-4 mr-2" />
                View Eco-Actions
              </Link>
            </Button>
          </CardContent>
        </Card>

        <Card className="shadow-elegant">
          <CardHeader>
            <CardTitle>Pending Eco-Actions</CardTitle>
            <CardDescription>Review student submissions</CardDescription>
          </CardHeader>
          <CardContent>
            {pendingActions.length === 0 ? (
              <p className="text-center text-muted-foreground py-8">No pending reviews</p>
            ) : (
              <div className="space-y-4 max-h-96 overflow-y-auto">
                {pendingActions.slice(0, 5).map((action) => (
                  <div key={action.id} className="border rounded-lg p-3 space-y-2">
                    <div>
                      <p className="font-medium text-sm">{action.title}</p>
                      <p className="text-xs text-muted-foreground">
                        By {action.student?.username}
                      </p>
                    </div>
                    <div className="flex gap-2">
                      <Button
                        size="sm"
                        onClick={() => handleReviewAction(action.id, 'approved')}
                      >
                        Approve
                      </Button>
                      <Button
                        size="sm"
                        variant="destructive"
                        onClick={() => handleReviewAction(action.id, 'rejected')}
                      >
                        Reject
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      <Card className="shadow-elegant">
        <CardHeader>
          <CardTitle>Recent Quiz Results</CardTitle>
          <CardDescription>Student quiz performance</CardDescription>
        </CardHeader>
        <CardContent>
          {quizResults.length === 0 ? (
            <p className="text-center text-muted-foreground py-8">No quiz results yet</p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Student</TableHead>
                  <TableHead>Quiz</TableHead>
                  <TableHead>Score</TableHead>
                  <TableHead>Points Earned</TableHead>
                  <TableHead>Date</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {quizResults.map((result: any) => (
                  <TableRow key={result.id}>
                    <TableCell>{result.student?.username || 'Unknown'}</TableCell>
                    <TableCell>{result.quiz?.title || 'Unknown Quiz'}</TableCell>
                    <TableCell>{result.score}/{result.total_questions}</TableCell>
                    <TableCell className="text-primary font-medium">{result.points_earned}</TableCell>
                    <TableCell>{new Date(result.completed_at).toLocaleDateString()}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      <Card className="shadow-elegant">
        <CardHeader>
          <CardTitle>Recent Game Results</CardTitle>
          <CardDescription>Student game performance</CardDescription>
        </CardHeader>
        <CardContent>
          {gameResults.length === 0 ? (
            <p className="text-center text-muted-foreground py-8">No game results yet</p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Student</TableHead>
                  <TableHead>Game</TableHead>
                  <TableHead>Score</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Points Earned</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {gameResults.map((result: any) => (
                  <TableRow key={result.id}>
                    <TableCell>{result.student?.username || 'Unknown'}</TableCell>
                    <TableCell>{result.challenge?.title || 'Unknown Game'}</TableCell>
                    <TableCell>{result.score}%</TableCell>
                    <TableCell>
                      {result.completed ? (
                        <span className="text-success">✓ Completed</span>
                      ) : (
                        <span className="text-muted-foreground">In Progress</span>
                      )}
                    </TableCell>
                    <TableCell className="text-primary font-medium">{result.points_earned}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

