import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ecoActionsApi, quizzesApi, quizAttemptsApi, challengeProgressApi, challengesApi, profilesApi } from '@/db/api';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { Award, Upload, BookOpen, Users, FileText, Gamepad2, Trophy, CheckCircle, XCircle, Clock, Plus, Edit, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import type { EcoActionWithDetails, QuizWithQuestions, Challenge } from '@/types/types';

export default function TeacherDashboard() {
  const [searchParams, setSearchParams] = useSearchParams();
  const [pendingActions, setPendingActions] = useState<EcoActionWithDetails[]>([]);
  const [allEcoActions, setAllEcoActions] = useState<EcoActionWithDetails[]>([]);
  const [quizzes, setQuizzes] = useState<QuizWithQuestions[]>([]);
  const [challenges, setChallenges] = useState<Challenge[]>([]);
  const [quizResults, setQuizResults] = useState<any[]>([]);
  const [gameResults, setGameResults] = useState<any[]>([]);
  const [leaderboardData, setLeaderboardData] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  
  // Get active tab from URL query parameter, default to 'overview'
  const activeTab = searchParams.get('tab') || 'overview';

  useEffect(() => {
    loadData();
  }, []);

  const handleTabChange = (value: string) => {
    setSearchParams({ tab: value });
  };

  const loadData = async () => {
    try {
      const [actionsData, quizzesData, attemptsData, progressData, challengesData, allActionsData, studentsData] = await Promise.all([
        ecoActionsApi.getPendingActions(),
        quizzesApi.getAllQuizzes(),
        quizAttemptsApi.getAllAttempts(),
        challengeProgressApi.getAllProgress(),
        challengesApi.getAllChallenges(),
        ecoActionsApi.getAllActions(),
        profilesApi.getAllProfiles(),
      ]);
      
      setPendingActions(actionsData);
      setAllEcoActions(allActionsData);
      setQuizzes(quizzesData);
      setChallenges(challengesData);
      setQuizResults(attemptsData);
      setGameResults(progressData);
      
      // Calculate leaderboard data
      const students = studentsData.filter(p => p.role === 'student');
      const leaderboard = students
        .map(student => {
          const quizAttempts = attemptsData.filter(a => a.student_id === student.id);
          const gameProgress = progressData.filter(g => g.student_id === student.id);
          const completedGames = gameProgress.filter(g => g.completed).length;
          
          return {
            ...student,
            quizAttempts: quizAttempts.length,
            gamesPlayed: gameProgress.length,
            gamesCompleted: completedGames,
            avgQuizScore: quizAttempts.length > 0 
              ? (quizAttempts.reduce((sum, a) => sum + (a.score / a.total_questions * 100), 0) / quizAttempts.length).toFixed(1)
              : 0,
          };
        })
        .sort((a, b) => b.total_points - a.total_points);
      
      setLeaderboardData(leaderboard);
    } catch (error) {
      console.error('Error loading data:', error);
      toast.error('Failed to load dashboard data');
    } finally {
      setLoading(false);
    }
  };

  const handleReviewAction = async (actionId: string, status: 'approved' | 'rejected') => {
    try {
      const user = await import('@/db/api').then(m => m.profilesApi.getCurrentUser());
      if (!user) return;

      await ecoActionsApi.reviewAction(actionId, status, user.id);
      toast.success(`Eco-action ${status}`);
      loadData();
    } catch (error) {
      console.error('Error reviewing action:', error);
      toast.error('Failed to review eco-action');
    }
  };

  const generateStudentReport = () => {
    const totalQuizAttempts = quizResults.length;
    const totalGamesPlayed = gameResults.length;
    const completedGames = gameResults.filter(g => g.completed).length;
    
    const report = `
=== STUDENT PERFORMANCE REPORT ===
Generated by: Teacher
Date: ${new Date().toLocaleString()}

QUIZ PERFORMANCE:
- Total Quiz Attempts: ${totalQuizAttempts}
${quizResults.slice(0, 10).map((result: any, i: number) => 
  `${i + 1}. ${result.student?.username || 'Unknown'} - ${result.quiz?.title || 'Unknown Quiz'} - Score: ${result.score}/${result.total_questions} - Points: ${result.points_earned}`
).join('\n')}

GAME PERFORMANCE:
- Total Games Played: ${totalGamesPlayed}
- Completed Games: ${completedGames}
${gameResults.slice(0, 10).map((result: any, i: number) => 
  `${i + 1}. ${result.student?.username || 'Unknown'} - ${result.challenge?.title || 'Unknown Game'} - Score: ${result.score}% - ${result.completed ? 'Completed' : 'In Progress'} - Points: ${result.points_earned}`
).join('\n')}

PENDING ECO-ACTIONS:
- Total Pending: ${pendingActions.length}
${pendingActions.slice(0, 5).map((action: any, i: number) => 
  `${i + 1}. ${action.student?.username || 'Unknown'} - ${action.title} - ${action.action_type}`
).join('\n')}

=== END OF REPORT ===
    `;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `student-report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Student report generated successfully!');
  };

  if (loading) {
    return (
      <div className="container mx-auto px-4 py-8 space-y-6">
        <Skeleton className="h-10 w-64 bg-muted" />
        <div className="grid gap-6 md:grid-cols-2">
          {[...Array(4)].map((_, i) => (
            <Card key={i}>
              <CardHeader>
                <Skeleton className="h-6 w-48 bg-muted" />
              </CardHeader>
              <CardContent>
                <Skeleton className="h-20 w-full bg-muted" />
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 py-8 space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold gradient-text">Teacher Dashboard</h1>
          <p className="text-muted-foreground">Manage content and review student activities</p>
        </div>
        <Button onClick={generateStudentReport}>
          <FileText className="w-4 h-4 mr-2" />
          Generate Report
        </Button>
      </div>

      <div className="grid gap-6 md:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Total Quizzes</CardTitle>
            <Award className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{quizzes.length}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Total Games</CardTitle>
            <Gamepad2 className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{challenges.length}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Pending Reviews</CardTitle>
            <Clock className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{pendingActions.length}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Total Students</CardTitle>
            <Users className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{leaderboardData.length}</div>
          </CardContent>
        </Card>
      </div>

      <Tabs value={activeTab} onValueChange={handleTabChange} className="space-y-6">
        <TabsList className="grid w-full grid-cols-4">
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="quizzes">Manage Quizzes</TabsTrigger>
          <TabsTrigger value="games">Manage Games</TabsTrigger>
          <TabsTrigger value="leaderboard">Leaderboard</TabsTrigger>
        </TabsList>

        {/* Overview Tab */}
        <TabsContent value="overview" className="space-y-6">
          <div className="grid gap-6 md:grid-cols-2">
            <Card>
              <CardHeader>
                <CardTitle>Recent Quiz Results</CardTitle>
                <CardDescription>Latest student quiz attempts</CardDescription>
              </CardHeader>
              <CardContent>
                {quizResults.length === 0 ? (
                  <p className="text-center text-muted-foreground py-8">No quiz results yet</p>
                ) : (
                  <div className="space-y-3 max-h-96 overflow-y-auto">
                    {quizResults.slice(0, 10).map((result: any) => (
                      <div key={result.id} className="flex items-center justify-between p-3 rounded-lg bg-accent">
                        <div>
                          <p className="font-medium text-sm">{result.student?.username || 'Unknown'}</p>
                          <p className="text-xs text-muted-foreground">{result.quiz?.title || 'Unknown Quiz'}</p>
                        </div>
                        <div className="text-right">
                          <p className="font-bold text-primary">{result.score}/{result.total_questions}</p>
                          <p className="text-xs text-muted-foreground">{result.points_earned} pts</p>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Recent Game Results</CardTitle>
                <CardDescription>Latest student game completions</CardDescription>
              </CardHeader>
              <CardContent>
                {gameResults.length === 0 ? (
                  <p className="text-center text-muted-foreground py-8">No game results yet</p>
                ) : (
                  <div className="space-y-3 max-h-96 overflow-y-auto">
                    {gameResults.slice(0, 10).map((result: any) => (
                      <div key={result.id} className="flex items-center justify-between p-3 rounded-lg bg-accent">
                        <div>
                          <p className="font-medium text-sm">{result.student?.username || 'Unknown'}</p>
                          <p className="text-xs text-muted-foreground">{result.challenge?.title || 'Unknown Game'}</p>
                        </div>
                        <div className="text-right">
                          <p className="font-bold text-primary">{result.score}%</p>
                          <Badge variant={result.completed ? 'default' : 'secondary'} className="text-xs">
                            {result.completed ? 'Completed' : 'In Progress'}
                          </Badge>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>
          </div>

          <Card>
            <CardHeader>
              <CardTitle>Pending Eco-Actions</CardTitle>
              <CardDescription>Review and approve student submissions</CardDescription>
            </CardHeader>
            <CardContent>
              {pendingActions.length === 0 ? (
                <p className="text-center text-muted-foreground py-8">No pending reviews</p>
              ) : (
                <div className="space-y-4">
                  {pendingActions.map((action) => (
                    <div key={action.id} className="border rounded-lg p-4 space-y-3">
                      <div className="flex items-start justify-between">
                        <div>
                          <p className="font-medium">{action.title}</p>
                          <p className="text-sm text-muted-foreground">
                            By {action.student?.username} • {action.action_type}
                          </p>
                          {action.description && (
                            <p className="text-sm mt-2">{action.description}</p>
                          )}
                        </div>
                        <Badge variant="secondary">Pending</Badge>
                      </div>
                      <div className="flex gap-2">
                        <Button
                          size="sm"
                          onClick={() => handleReviewAction(action.id, 'approved')}
                        >
                          <CheckCircle className="w-4 h-4 mr-1" />
                          Approve
                        </Button>
                        <Button
                          size="sm"
                          variant="destructive"
                          onClick={() => handleReviewAction(action.id, 'rejected')}
                        >
                          <XCircle className="w-4 h-4 mr-1" />
                          Reject
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Manage Quizzes Tab */}
        <TabsContent value="quizzes" className="space-y-6">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between">
              <div>
                <CardTitle>Quiz Management</CardTitle>
                <CardDescription>Add, edit, or delete quizzes</CardDescription>
              </div>
              <Button asChild>
                <Link to="/quizzes">
                  <Plus className="w-4 h-4 mr-2" />
                  Add New Quiz
                </Link>
              </Button>
            </CardHeader>
            <CardContent>
              {quizzes.length === 0 ? (
                <p className="text-center text-muted-foreground py-8">No quizzes created yet</p>
              ) : (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Quiz Title</TableHead>
                      <TableHead>Category</TableHead>
                      <TableHead>Questions</TableHead>
                      <TableHead>Attempts</TableHead>
                      <TableHead>Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {quizzes.map((quiz) => {
                      const attempts = quizResults.filter(r => r.quiz_id === quiz.id).length;
                      return (
                        <TableRow key={quiz.id}>
                          <TableCell className="font-medium">{quiz.title}</TableCell>
                          <TableCell>
                            <Badge variant="outline">{quiz.topic?.title || 'General'}</Badge>
                          </TableCell>
                          <TableCell>{quiz.questions?.length || 0}</TableCell>
                          <TableCell>{attempts}</TableCell>
                          <TableCell>
                            <div className="flex gap-2">
                              <Button size="sm" variant="outline" asChild>
                                <Link to={`/quiz/${quiz.id}`}>
                                  <Edit className="w-4 h-4" />
                                </Link>
                              </Button>
                            </div>
                          </TableCell>
                        </TableRow>
                      );
                    })}
                  </TableBody>
                </Table>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Manage Games Tab */}
        <TabsContent value="games" className="space-y-6">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between">
              <div>
                <CardTitle>Game Management</CardTitle>
                <CardDescription>Add, edit, or delete games/challenges</CardDescription>
              </div>
              <Button asChild>
                <Link to="/challenges">
                  <Plus className="w-4 h-4 mr-2" />
                  Add New Game
                </Link>
              </Button>
            </CardHeader>
            <CardContent>
              {challenges.length === 0 ? (
                <p className="text-center text-muted-foreground py-8">No games created yet</p>
              ) : (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Game Title</TableHead>
                      <TableHead>Type</TableHead>
                      <TableHead>Points</TableHead>
                      <TableHead>Completions</TableHead>
                      <TableHead>Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {challenges.map((challenge) => {
                      const completions = gameResults.filter(r => r.challenge_id === challenge.id && r.completed).length;
                      return (
                        <TableRow key={challenge.id}>
                          <TableCell className="font-medium">{challenge.title}</TableCell>
                          <TableCell>
                            <Badge variant="outline">{challenge.challenge_type}</Badge>
                          </TableCell>
                          <TableCell className="text-primary font-medium">{challenge.points_reward}</TableCell>
                          <TableCell>{completions}</TableCell>
                          <TableCell>
                            <div className="flex gap-2">
                              <Button size="sm" variant="outline" asChild>
                                <Link to={`/challenge/${challenge.id}`}>
                                  <Edit className="w-4 h-4" />
                                </Link>
                              </Button>
                            </div>
                          </TableCell>
                        </TableRow>
                      );
                    })}
                  </TableBody>
                </Table>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Leaderboard Tab */}
        <TabsContent value="leaderboard" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Student Leaderboard</CardTitle>
              <CardDescription>View student performance and rankings</CardDescription>
            </CardHeader>
            <CardContent>
              {leaderboardData.length === 0 ? (
                <p className="text-center text-muted-foreground py-8">No student data available</p>
              ) : (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Rank</TableHead>
                      <TableHead>Student</TableHead>
                      <TableHead>Total Points</TableHead>
                      <TableHead>Quiz Attempts</TableHead>
                      <TableHead>Avg Quiz Score</TableHead>
                      <TableHead>Games Played</TableHead>
                      <TableHead>Games Completed</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {leaderboardData.map((student, index) => (
                      <TableRow key={student.id}>
                        <TableCell>
                          <div className="flex items-center gap-2">
                            {index < 3 && <Trophy className={`w-4 h-4 ${
                              index === 0 ? 'text-yellow-500' : 
                              index === 1 ? 'text-gray-400' : 
                              'text-amber-600'
                            }`} />}
                            <span className="font-bold">#{index + 1}</span>
                          </div>
                        </TableCell>
                        <TableCell className="font-medium">{student.username}</TableCell>
                        <TableCell className="text-primary font-bold">{student.total_points}</TableCell>
                        <TableCell>{student.quizAttempts}</TableCell>
                        <TableCell>{student.avgQuizScore}%</TableCell>
                        <TableCell>{student.gamesPlayed}</TableCell>
                        <TableCell>{student.gamesCompleted}</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>All Eco-Actions</CardTitle>
              <CardDescription>View all submitted eco-actions by students</CardDescription>
            </CardHeader>
            <CardContent>
              {allEcoActions.length === 0 ? (
                <p className="text-center text-muted-foreground py-8">No eco-actions submitted yet</p>
              ) : (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Student</TableHead>
                      <TableHead>Title</TableHead>
                      <TableHead>Type</TableHead>
                      <TableHead>Status</TableHead>
                      <TableHead>Date</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {allEcoActions.map((action) => (
                      <TableRow key={action.id}>
                        <TableCell className="font-medium">{action.student?.username || 'Unknown'}</TableCell>
                        <TableCell>{action.title}</TableCell>
                        <TableCell>
                          <Badge variant="outline">{action.action_type}</Badge>
                        </TableCell>
                        <TableCell>
                          <Badge variant={
                            action.status === 'approved' ? 'default' : 
                            action.status === 'rejected' ? 'destructive' : 
                            'secondary'
                          }>
                            {action.status}
                          </Badge>
                        </TableCell>
                        <TableCell>{new Date(action.submitted_at).toLocaleDateString()}</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}

